# Numpy
    Benefits of Numpy Array
       1. Less Memory
       2. Fast
       3. Convinient

In [9]:
import numpy as np 
import time
import sys

In [4]:
alist = [1,3,5,6,5,7]
uplist = np.array(alist)
print(type(uplist))

<class 'numpy.ndarray'>


In [6]:
npArray = np.array([1,4,6, "ALI", 0.6])
print(npArray)

['1' '4' '6' 'ALI' '0.6']


In [11]:
npArray[0:5]

array(['1', '4', '6', 'ALI', '0.6'], dtype='<U32')

In [14]:
npArray[-1:]

array(['0.6'], dtype='<U32')

In [26]:
l = range(1000)
print(sys.getsizeof(5)*len(l))


28000


In [28]:
array = np.arange(1000)
print(array.size*array.itemsize)

4000


In [34]:
#List and Array (Numpy)
size = 1000000

l1 = range(size)
l2 = range(size)

a1 = np.arange(size)
a2 = np.arange(size)

#list print
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("Python list took : ", (time.time()-start)*1000)

#Array Numpy print
start= time.time()
result = a1+a2
print("Python list took : ", (time.time()-start)*1000)
# print(type(a1))

Python list took :  166.55302047729492
Python list took :  13.962507247924805


# Numpy tutorial - basic array operations

In [1]:
import numpy as np

In [4]:
a = np.array([5,6,9])
a[0]

5

In [5]:
a[1]

6

In [7]:
a=np.array([
    [1,2], [3,4], [5,6]
])
a.ndim

2

In [8]:
a = np.array([5,6,8])
a.ndim

1

In [9]:
a.itemsize

4

In [15]:
a=np.array([
    [1,2], [3,4], [5,6]
], dtype=np.float64)
print(a)
print(a.itemsize)

[[1. 2.]
 [3. 4.]
 [5. 6.]]
8


In [13]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [16]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
a = 4*(np.ones((3,4)))
a

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [36]:
l=range(1,5)
l

range(1, 5, 2)

In [32]:
l[1]

1

In [35]:
np.arange(1,5,2)

array([1, 3])

In [37]:
a=np.array([[1,2], [3,4], [5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
a.shape

(3, 2)

In [40]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [43]:
a=np.array([[1,2], [3,4], [5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
a.sum()

21

In [45]:
a.max()

6

In [46]:
a.min()

1

In [47]:
a.sum(axis=0) #Axi=0 Culumn Addition 

array([ 9, 12])

In [48]:
a.sum(axis=1) #Axi=1 Rows Addition

array([ 3,  7, 11])

In [49]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [50]:
np.std(a)

1.707825127659933

In [51]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])


In [52]:
a

array([[1, 2],
       [3, 4]])

In [53]:
b

array([[5, 6],
       [7, 8]])

In [56]:
print(a+b)
print("-------------")
print(a-b)
print("-------------")
print(a*b)
print("-------------")
print(a/b)

[[ 6  8]
 [10 12]]
-------------
[[-4 -4]
 [-4 -4]]
-------------
[[ 5 12]
 [21 32]]
-------------
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [57]:
a.dot(b)

array([[19, 22],
       [43, 50]])

# Numpy - Indexing & Slicing

In [5]:
n = [6,7,8]
n[0:2]

[6, 7]

In [6]:
n[-1]

8

In [7]:
type(n)

list

In [10]:
a = np.array([6,7,8])
a[0:2]

array([6, 7])

In [12]:
a[-1]

8

In [14]:
a = np.array([[6,7,8], [1,2,3], [9,8,7] ])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 8, 7]])

In [17]:
a[0,2] #First row and 2nd column value

8

In [20]:
a[0:2, 2] 

array([8, 3])

# Iterating through Loop

In [21]:
a = np.array([[6,7,8], [1,2,3], [9,8,7] ])


In [22]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 8 7]


In [23]:
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
8
7


In [26]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)

In [27]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [28]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [29]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [30]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [31]:
a = np.arange(12).reshape(3,4)

In [32]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
b = a >4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [34]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [35]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [36]:
a[b]=-1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

# Run with Loop

In [2]:
import numpy as np

In [3]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
for row in a.flatten():
    print(row)

0
1
2
3
4
5
6
7
8
9
10
11


In [11]:
for x in np.nditer(a,order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [12]:
for x in np.nditer(a,order='F', flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]
