# Numpy Tutorial - CDW

In [1]:
import numpy as np

In [5]:
myarr = np.array([3,6,32,7], np.int8)

In [15]:
myarr[0,1]

6

In [8]:
myarr

array([[ 3,  6, 32,  7]], dtype=int8)

In [17]:
myarr.shape


(1, 4)

# Array Creation : Conversion

In [20]:
larray = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [21]:
larray 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
larray.shape

(3, 3)

In [26]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
larray.dtype

dtype('int32')

In [28]:
larray.size

9

In [29]:
zeros = np.zeros((2,5))

In [30]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
zeros.shape

(2, 5)

In [32]:
rng = np.arange(15)

In [33]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
lspace = np.linspace(1,60,10)

In [38]:
lspace

array([ 1.        ,  7.55555556, 14.11111111, 20.66666667, 27.22222222,
       33.77777778, 40.33333333, 46.88888889, 53.44444444, 60.        ])

In [40]:
emp = np.empty((4,6))

In [41]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        9.34609111e-307, 1.33511018e-306, 1.33511969e-306],
       [6.23037996e-307, 6.23053954e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307, 9.34603000e-307],
       [1.78018403e-306, 8.90106955e-307, 1.60218491e-306,
        1.78018403e-306, 1.69119330e-306, 6.23054633e-307],
       [1.60219578e-306, 7.56601165e-307, 6.23061763e-307,
        8.90104239e-307, 1.37961573e-306, 9.34604358e-307]])

In [42]:
ide = np.identity(45)

In [43]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [45]:
arr = np.arange(99)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [47]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [48]:
arr.shape

(99,)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [50]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

 AXIS in NUMPY

In [51]:
x = [[1,2,3], [4,5,6], [7,8,9]]

In [52]:
arr = np.array(x)

In [53]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
arr.sum(axis=0)

array([12, 15, 18])

In [58]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [59]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [60]:
arr.flat

In [61]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [62]:
 arr.ndim

2

In [63]:
arr.size

9

In [64]:
arr.shape

(3, 3)

In [65]:
arr.nbytes

36

In [66]:
one = np.array([1,3,4,634,2])

In [67]:
one.argmax()

3

In [68]:
one.argmin()

0

In [69]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [70]:
ar

NameError: name 'ar' is not defined

In [72]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
arr2 = np.array([[1,2,1], [4,0,6],[8,1,0]])

In [77]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
arr2 

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [75]:
arr + arr2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  9,  9]])

In [79]:
arr.max()

9