# Numpy
    - Numerical Python
    - Fastest
    - Vectorised Operaton
    - Contigous Memory

In [2]:
import numpy as np

In [2]:
#creating an array unsing a python listb
x = np.array([22,33,44,55])
x

array([22, 33, 44, 55])

In [3]:
x.size

4

In [5]:
#1d = Vector
#2d = Matrix 
#3d = Cube
#nd = ....

x.shape

(4,)

In [6]:
x.ndim

1

In [8]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr2d = np.array([[1,2,3],[11,22,33],[111,222,333],[1111,2222,3333]])
arr2d

array([[   1,    2,    3],
       [  11,   22,   33],
       [ 111,  222,  333],
       [1111, 2222, 3333]])

In [14]:
arr2d.shape

(4, 3)

In [15]:
arr2d.ndim

2

In [39]:
# arr2d = np.arange(20).reshape(1,20)
# arr2d = np.arange(20).reshape(20,1)
# arr2d = np.arange(20).reshape(4,5)
# arr2d = np.arange(20).reshape(5,4)
# arr2d = np.arange(20).reshape(10,2)
arr2d = np.arange(20).reshape(2,10)
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [40]:
arr2d.shape

(2, 10)

In [25]:
arr2d.ndim

2

# 3D - Cubic Array

In [28]:
arr3d = np.arange(64).reshape(4,4,4) #depth, row, col
                        #FOR ML => Matrixnum, row, col
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [29]:
arr3d.shape

(4, 4, 4)

In [30]:
arr3d.ndim

3

In [41]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [49]:
arr2d[1,6]

array([16, 17, 18])

In [50]:
arr2d[1][6]

16

In [51]:
x

array([22, 33, 44, 55])

In [52]:
z = []

for n in x:
    z.append(n*2)
    
z

[44, 66, 88, 110]

In [53]:
[n**2 for n in x]

[484, 1089, 1936, 3025]

In [54]:
arr2d = np.arange(20).reshape(4,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [55]:
arr2d/10

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4],
       [1.5, 1.6, 1.7, 1.8, 1.9]])

In [56]:
arr2d**2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361]], dtype=int32)

In [57]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [59]:
arr3d*10

array([[[  0,  10,  20,  30],
        [ 40,  50,  60,  70],
        [ 80,  90, 100, 110],
        [120, 130, 140, 150]],

       [[160, 170, 180, 190],
        [200, 210, 220, 230],
        [240, 250, 260, 270],
        [280, 290, 300, 310]],

       [[320, 330, 340, 350],
        [360, 370, 380, 390],
        [400, 410, 420, 430],
        [440, 450, 460, 470]],

       [[480, 490, 500, 510],
        [520, 530, 540, 550],
        [560, 570, 580, 590],
        [600, 610, 620, 630]]])

In [60]:
x

array([22, 33, 44, 55])

In [62]:
y = np.arange(4)
y

array([0, 1, 2, 3])

In [63]:
x+y

array([22, 34, 46, 58])

# Mirroring = Elementwise Operations

In [65]:
a = np.arange(25).reshape(5,5)
b = np.arange(25,50).reshape(5,5)

In [66]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [67]:
b

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [68]:
#Mirror Multiplication or Element wise

#Adding
a+b

array([[25, 27, 29, 31, 33],
       [35, 37, 39, 41, 43],
       [45, 47, 49, 51, 53],
       [55, 57, 59, 61, 63],
       [65, 67, 69, 71, 73]])

In [70]:
#Multiply
a*b

array([[   0,   26,   54,   84,  116],
       [ 150,  186,  224,  264,  306],
       [ 350,  396,  444,  494,  546],
       [ 600,  656,  714,  774,  836],
       [ 900,  966, 1034, 1104, 1176]])

In [72]:
#New Sign - Linear Algebra Multiplication
a@b
# a.dot(b)

array([[ 400,  410,  420,  430,  440],
       [1275, 1310, 1345, 1380, 1415],
       [2150, 2210, 2270, 2330, 2390],
       [3025, 3110, 3195, 3280, 3365],
       [3900, 4010, 4120, 4230, 4340]])

In [73]:
c = np.arange(20).reshape(5,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [74]:
#Shape Different b=(5,5) and c=(5,4)
b@c

array([[1120, 1255, 1390, 1525],
       [1320, 1480, 1640, 1800],
       [1520, 1705, 1890, 2075],
       [1720, 1930, 2140, 2350],
       [1920, 2155, 2390, 2625]])

In [75]:
#c=(5,4)
c@b 

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 4)

# Slicing

In [76]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [77]:
a[2,3]

13

In [ ]:
# array [row,       col]
#      [start:end,  start:end]

In [78]:
a[2:3, 3:4]

array([[13]])

In [79]:
a[1:4,3]

array([ 8, 13, 18])

In [84]:
a[1:4, 3:4]

array([[ 8],
       [13],
       [18]])

# Querring Array

In [85]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [87]:
#mask
a>5 #Broadcasting

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [88]:
mask = a>5
mask

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [89]:
a[mask]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24])

In [90]:
a[a>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [95]:
a[a>7] = 100
a

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [97]:
np.where(a>10, 0, a) 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [98]:
a[(a%2==0) & (a%7==0)]

array([0])

In [99]:
a

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [100]:
a[(a%2==0) | (a%7==0)]

array([  0,   2,   4,   6,   7, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100])

In [104]:
np.where((a%2==0) | (a%7==0), "Wow", "Oh")

array([['Wow', 'Oh', 'Wow', 'Oh', 'Wow'],
       ['Oh', 'Wow', 'Wow', 'Wow', 'Wow'],
       ['Wow', 'Wow', 'Wow', 'Wow', 'Wow'],
       ['Wow', 'Wow', 'Wow', 'Wow', 'Wow'],
       ['Wow', 'Wow', 'Wow', 'Wow', 'Wow']], dtype='<U3')

# COMBINING ARRAYS

In [105]:
a

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [106]:
b

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [108]:
np.concatenate((a,b))

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49]])

In [110]:
np.concatenate((a,b), axis=1) #axis=0 row and axis=1 col

array([[  0,   1,   2,   3,   4,  25,  26,  27,  28,  29],
       [  5,   6,   7, 100, 100,  30,  31,  32,  33,  34],
       [100, 100, 100, 100, 100,  35,  36,  37,  38,  39],
       [100, 100, 100, 100, 100,  40,  41,  42,  43,  44],
       [100, 100, 100, 100, 100,  45,  46,  47,  48,  49]])

In [111]:
np.stack((a,b))

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100]],

       [[ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49]]])

In [113]:
a.max()

100

In [3]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
10*(np.ones((5,5)))

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [6]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
strings = ["foo", "bar", "baz", "foo", "qux"]
print(set(strings))

{'baz', 'qux', 'bar', 'foo'}


In [27]:
strings = ["foo", "bar", "baz", "foo", "qux"]
unique_strings = []

for string in strings:
    if string not in unique_strings:
        unique_strings.append(string)

print(unique_strings)

['foo', 'bar', 'baz', 'qux']
