# PANDAS
    - Data Analysis Library
    - Series (Single Dimension)
    - DataFrame (Multi Dimensional)
    - 

In [49]:
import pandas as pd
import numpy as np

# SERIES

In [28]:
s1 = pd.Series([1,2,3,4])
type(s1)

pandas.core.series.Series

In [29]:
print(s1)

0    1
1    2
2    3
3    4
dtype: int64


In [30]:
s1.index

RangeIndex(start=0, stop=4, step=1)

In [31]:
s1.values

array([1, 2, 3, 4], dtype=int64)

In [32]:
s1.index = ['one', 'two', 'three', 'four']
s1

one      1
two      2
three    3
four     4
dtype: int64

In [33]:
s1['one']

1

In [34]:
s2 = pd.Series([22,33,44,55, 34], index=['apples', 'oranges', 'bananas', 'gauvas', 'four'])
s2

apples     22
oranges    33
bananas    44
gauvas     55
four       34
dtype: int64

In [35]:
s2['apples']

22

In [36]:
s1

one      1
two      2
three    3
four     4
dtype: int64

In [37]:
s2

apples     22
oranges    33
bananas    44
gauvas     55
four       34
dtype: int64

In [40]:
s1 + s2


apples      NaN
bananas     NaN
four       38.0
gauvas      NaN
one         NaN
oranges     NaN
three       NaN
two         NaN
dtype: float64

In [41]:
s3 = pd.Series(range(10))
s3

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [47]:
s4 = pd.Series(range(10,21))
s4

0     10
1     11
2     12
3     13
4     14
5     15
6     16
7     17
8     18
9     19
10    20
dtype: int64

In [48]:
s3+s4

0     10.0
1     12.0
2     14.0
3     16.0
4     18.0
5     20.0
6     22.0
7     24.0
8     26.0
9     28.0
10     NaN
dtype: float64

In [51]:
arr1 = np.arange(5)
arr1

array([0, 1, 2, 3, 4])

In [53]:
arr2 = np.arange(6)
arr2

array([0, 1, 2, 3, 4, 5])

In [54]:
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [55]:
s2[2:4]

bananas    44
gauvas     55
dtype: int64

In [59]:
s2['oranges':'gauvas']

oranges    33
bananas    44
gauvas     55
dtype: int64

# Lambda Functions: Anonymous Functions (IIF)

In [79]:
new = pd.Series([99, 100, 50, 45, 30, 30], index=['Ahmed', 'Ali', 'Faisal', 'Hassan', 'Mehfooz', 'wajid'])
new

Ahmed       99
Ali        100
Faisal      50
Hassan      45
Mehfooz     30
wajid       30
dtype: int64

In [66]:
def myfunc(marks):
    return marks/100

new.apply(myfunc)

Ahmed      0.99
Ali        1.00
Faisal     0.50
Hassan     0.45
Mehfooz    0.30
wajid      0.30
dtype: float64

In [69]:
new.apply(lambda x:x*100)

Ahmed       9900
Ali        10000
Faisal      5000
Hassan      4500
Mehfooz     3000
wajid       3000
dtype: int64

In [70]:
new.apply(lambda x: np.where(x>50, 'Pass', 'Fail'))

Ahmed      Pass
Ali        Pass
Faisal     Fail
Hassan     Fail
Mehfooz    Fail
wajid      Fail
dtype: object

In [71]:
s6 = pd.Series(100, index=s2.index)
s6

apples     100
oranges    100
bananas    100
gauvas     100
four       100
dtype: int64

In [72]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [73]:
new.count()

6

In [74]:
new.value_counts()

30     2
99     1
100    1
50     1
45     1
dtype: int64

In [83]:
new[['Ahmed','Mehfooz']]

Ahmed      99
Mehfooz    30
dtype: int64

In [87]:
s7 = pd.Series([1,2,3, np.nan, np.nan])
s7

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
dtype: float64

In [88]:
combined = pd.concat([s1,s2])
combined

one         1
two         2
three       3
four        4
apples     22
oranges    33
bananas    44
gauvas     55
four       34
dtype: int64

In [89]:
combined.reset_index()

index   0
0      one   1
1      two   2
2    three   3
3     four   4
4   apples  22
5  oranges  33
6  bananas  44
7   gauvas  55
8     four  34

In [91]:
combined.reset_index(drop=True, inplace=True)
combined

0     1
1     2
2     3
3     4
4    22
5    33
6    44
7    55
8    34
dtype: int64

In [98]:
combined[4] = 2444
combined

0       1
1       2
2       3
3       4
5      33
6      44
7      55
8      34
4    2444
dtype: int64

In [103]:
del combined[[1,3,5]]

TypeError: '[1, 3, 5]' is an invalid key

In [104]:
combined

0       1
1       2
2       3
3       4
5      33
6      44
7      55
8      34
4    2444
dtype: int64

In [105]:
newCom = combined.copy()

In [106]:
newCom

0       1
1       2
2       3
3       4
5      33
6      44
7      55
8      34
4    2444
dtype: int64

# Pandas Data Frame

In [152]:
students = {'rolls': [1,2,3,4,5,6],
           'names': ['Mehfooz', 'Wajid', 'Moona', 'Sadia','Rauf','Hassan'],
            'courses': ['Python', 'Numpy', 'Pandas', 'Numpy','Numpy', 'Numpy'],
            'mode': ['Onsite', 'Onsite','Onsite', 'Online','Onsite','Onsite']
           }

In [153]:
students

{'rolls': [1, 2, 3, 4, 5, 6],
 'names': ['Mehfooz', 'Wajid', 'Moona', 'Sadia', 'Rauf', 'Hassan'],
 'courses': ['Python', 'Numpy', 'Pandas', 'Numpy', 'Numpy', 'Numpy'],
 'mode': ['Onsite', 'Onsite', 'Onsite', 'Online', 'Onsite', 'Onsite']}

In [154]:
df = pd.DataFrame(students)
df



rolls    names courses    mode
0      1  Mehfooz  Python  Onsite
1      2    Wajid   Numpy  Onsite
2      3    Moona  Pandas  Onsite
3      4    Sadia   Numpy  Online
4      5     Rauf   Numpy  Onsite
5      6   Hassan   Numpy  Onsite

In [155]:
df['names']

0    Mehfooz
1      Wajid
2      Moona
3      Sadia
4       Rauf
5     Hassan
Name: names, dtype: object

In [156]:
df['mode']


0    Onsite
1    Onsite
2    Onsite
3    Online
4    Onsite
5    Onsite
Name: mode, dtype: object

In [157]:
lst = [[55,66,77],[2,4,5],[4,5,6]]
lst

[[55, 66, 77], [2, 4, 5], [4, 5, 6]]

In [158]:
df2 = pd.DataFrame(lst, index=[1,2,3], columns=['a','b','c'])
df2

a   b   c
1  55  66  77
2   2   4   5
3   4   5   6

In [159]:
df['counry'] = ['Pakistan', 'India', 'Austrailia', 'Japan', 'Indonesia', 'Pakistan']

In [160]:
df

rolls    names courses    mode      counry
0      1  Mehfooz  Python  Onsite    Pakistan
1      2    Wajid   Numpy  Onsite       India
2      3    Moona  Pandas  Onsite  Austrailia
3      4    Sadia   Numpy  Online       Japan
4      5     Rauf   Numpy  Onsite   Indonesia
5      6   Hassan   Numpy  Onsite    Pakistan

In [161]:
df['Ages'] = [23,43,23,54,22,45]

In [162]:
df

rolls    names courses    mode      counry  Ages
0      1  Mehfooz  Python  Onsite    Pakistan    23
1      2    Wajid   Numpy  Onsite       India    43
2      3    Moona  Pandas  Onsite  Austrailia    23
3      4    Sadia   Numpy  Online       Japan    54
4      5     Rauf   Numpy  Onsite   Indonesia    22
5      6   Hassan   Numpy  Onsite    Pakistan    45

In [189]:
dic = {'Mehfooz':22, 'Wajid':23, 'Moona':19, 'Sadia':24, 'Rauf':25, 'Hassan':23}

In [190]:
#Now Mapping Dictionary with DataFrame
df['New Ages'] = df.names.map(dic)

In [191]:
df

rolls    names courses    mode      counry  Ages Status            City  \
0      1  Mehfooz  Python  Onsite    Pakistan    23   Fail         Karachi   
1      2    Wajid   Numpy  Onsite       India    43   Pass         Karachi   
2      3    Moona  Pandas  Onsite  Austrailia    23   Fail         Karachi   
3      4    Sadia   Numpy  Online       Japan    54   Pass  Out of Karachi   
4      5     Rauf   Numpy  Onsite   Indonesia    22   Fail         Karachi   
5      6   Hassan   Numpy  Onsite    Pakistan    45   Pass         Karachi   

   Generation  New Ages  
0       Young        22  
1  Mature Man        23  
2       Young        19  
3  Mature Man        24  
4       Young        25  
5  Mature Man        23

In [192]:
df['Status'] = ['Pass' if age>25 else 'Fail' for age in df['Ages']]

In [193]:
df

rolls    names courses    mode      counry  Ages Status            City  \
0      1  Mehfooz  Python  Onsite    Pakistan    23   Fail         Karachi   
1      2    Wajid   Numpy  Onsite       India    43   Pass         Karachi   
2      3    Moona  Pandas  Onsite  Austrailia    23   Fail         Karachi   
3      4    Sadia   Numpy  Online       Japan    54   Pass  Out of Karachi   
4      5     Rauf   Numpy  Onsite   Indonesia    22   Fail         Karachi   
5      6   Hassan   Numpy  Onsite    Pakistan    45   Pass         Karachi   

   Generation  New Ages  
0       Young        22  
1  Mature Man        23  
2       Young        19  
3  Mature Man        24  
4       Young        25  
5  Mature Man        23

In [194]:
df['City'] = df['mode'].apply(lambda x : 'Karachi' if x=='Onsite' else 'Out of Karachi')

In [195]:
df

rolls    names courses    mode      counry  Ages Status            City  \
0      1  Mehfooz  Python  Onsite    Pakistan    23   Fail         Karachi   
1      2    Wajid   Numpy  Onsite       India    43   Pass         Karachi   
2      3    Moona  Pandas  Onsite  Austrailia    23   Fail         Karachi   
3      4    Sadia   Numpy  Online       Japan    54   Pass  Out of Karachi   
4      5     Rauf   Numpy  Onsite   Indonesia    22   Fail         Karachi   
5      6   Hassan   Numpy  Onsite    Pakistan    45   Pass         Karachi   

   Generation  New Ages  
0       Young        22  
1  Mature Man        23  
2       Young        19  
3  Mature Man        24  
4       Young        25  
5  Mature Man        23

In [196]:
def generationAssign(age):
    if age < 20:
        return 'Teen Ager'
    elif age<40:
        return 'Young'
    elif age<60:
        return 'Mature Man'
    else:
        return 'Senior'

In [197]:
df['Generation'] = df['New Ages'].apply(generationAssign)
# df['Generation'] = df.Ages.apply(generationAssign)

In [198]:
df

rolls    names courses    mode      counry  Ages Status            City  \
0      1  Mehfooz  Python  Onsite    Pakistan    23   Fail         Karachi   
1      2    Wajid   Numpy  Onsite       India    43   Pass         Karachi   
2      3    Moona  Pandas  Onsite  Austrailia    23   Fail         Karachi   
3      4    Sadia   Numpy  Online       Japan    54   Pass  Out of Karachi   
4      5     Rauf   Numpy  Onsite   Indonesia    22   Fail         Karachi   
5      6   Hassan   Numpy  Onsite    Pakistan    45   Pass         Karachi   

  Generation  New Ages  
0      Young        22  
1      Young        23  
2  Teen Ager        19  
3      Young        24  
4      Young        25  
5      Young        23

In [177]:
df

rolls    names courses    mode      counry  Ages Status            City  \
0      1  Mehfooz  Python  Onsite    Pakistan    23   Fail         Karachi   
1      2    Wajid   Numpy  Onsite       India    43   Pass         Karachi   
2      3    Moona  Pandas  Onsite  Austrailia    23   Fail         Karachi   
3      4    Sadia   Numpy  Online       Japan    54   Pass  Out of Karachi   
4      5     Rauf   Numpy  Onsite   Indonesia    22   Fail         Karachi   
5      6   Hassan   Numpy  Onsite    Pakistan    45   Pass         Karachi   

   Generation  
0       Young  
1  Mature Man  
2       Young  
3  Mature Man  
4       Young  
5  Mature Man